# Generated by Django 4.2.7 on 2026-03-25 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Unique identifier', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('jmbg', models.CharField(blank=True, help_text='Unique Master Citizen Number (13 digits)', max_length=13, null=True, unique=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('place_of_residence', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('smoking_status', models.CharField(choices=[('never', 'Never smoked'), ('current', 'Current smoker'), ('former', 'Former smoker')], default='never', max_length=20)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('moderate', 'Moderate (<2 units/day)'), ('heavy', 'Heavy (>2 units/day)')], max_length=20)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('cardiovascular_disease', models.BooleanField(default=False)),
                ('chronic_kidney_disease', models.BooleanField(default=False)),
                ('copd', models.BooleanField(default=False)),
                ('liver_cirrhosis', models.BooleanField(default=False)),
                ('hepatitis_b', models.BooleanField(default=False)),
                ('hepatitis_c', models.BooleanField(default=False)),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
