# Generated by Django 4.2.7 on 2026-03-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='main_diagnosis',
            field=models.ForeignKey(blank=True, help_text='Main clinical diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='medical_codes.diagnosis'),
        ),
    ]
