# Generated by Django 4.2.7 on 2026-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_main_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_followup_date',
            field=models.DateField(blank=True, help_text='Date of most recent follow-up', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active Follow-up'), ('deceased', 'Deceased'), ('transferred', 'Transferred to other institution'), ('lost', 'Lost to Follow-up'), ('inactive', 'Inactive')], default='active', help_text='Current patient status', max_length=20),
        ),
    ]
