# Generated by Django 6.0.3 on 2026-03-28 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0001_initial'),
        ('patients', '0003_patient_last_followup_date_patient_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='alcohol_consumption',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cardiovascular_disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hepatitis_b',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hepatitis_c',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='liver_cirrhosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='place_of_residence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coronary_artery_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, default='Serbia', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, help_text='Medical Record Number', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='copd',
            field=models.BooleanField(default=False, help_text='Chronic Obstructive Pulmonary Disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='jmbg',
            field=models.CharField(blank=True, help_text='Unique Master Citizen Number (JMBG)', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='main_diagnosis',
            field=models.ForeignKey(blank=True, help_text='Primary ICD-10 diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='medical_codes.diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text='Unique patient identifier (e.g., hospital ID)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('current', 'Current smoker')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patient_id_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
    ]
