# Generated by Django 6.0.3 on 2026-03-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_followup_date',
        ),
    ]
