# Generated by Django 4.2.7 on 2026-03-25 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField()),
                ('procedure_type', models.CharField(choices=[('pancreaticoduodenectomy', 'Pancreaticoduodenectomy (Whipple)'), ('distal_pancreatectomy', 'Distal Pancreatectomy'), ('central_pancreatectomy', 'Central Pancreatectomy'), ('total_pancreatectomy', 'Total Pancreatectomy'), ('hepatectomy_major', 'Major Hepatectomy (≥3 segments)'), ('hepatectomy_minor', 'Minor Hepatectomy (<3 segments)'), ('cholecystectomy', 'Cholecystectomy'), ('bile_duct_resection', 'Bile Duct Resection'), ('liver_transplant', 'Liver Transplantation')], max_length=50)),
                ('operative_time_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('blood_loss_ml', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('intraoperative_transfusion', models.BooleanField(default=False)),
                ('transfusion_units', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pringle_maneuver', models.BooleanField(default=False)),
                ('pringle_time_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('popf_present', models.BooleanField(default=False)),
                ('popf_grade', models.CharField(blank=True, choices=[('A', 'Grade A (Biochemical leak)'), ('B', 'Grade B (Requires intervention)'), ('C', 'Grade C (Severe, reoperation/death)')], max_length=1, null=True)),
                ('popf_drain_amylase', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('clavien_dindo_grade', models.IntegerField(blank=True, choices=[(0, 'No complication'), (1, 'Grade I - Any deviation from normal course'), (2, 'Grade II - Pharmacologic treatment'), (3, 'Grade IIIa - Intervention without general anesthesia'), (3, 'Grade IIIb - Intervention with general anesthesia'), (4, 'Grade IVa - Single organ dysfunction'), (4, 'Grade IVb - Multiorgan dysfunction'), (5, 'Grade V - Death')], null=True)),
                ('bile_leak', models.BooleanField(default=False)),
                ('bile_leak_grade', models.CharField(blank=True, choices=[('A', 'Grade A - Managed conservatively'), ('B', 'Grade B - Requires intervention'), ('C', 'Grade C - Reoperation required')], max_length=1, null=True)),
                ('bile_leak_treatment', models.TextField(blank=True)),
                ('hospital_stay_days', models.IntegerField(blank=True, null=True)),
                ('icu_stay_days', models.IntegerField(blank=True, null=True)),
                ('readmission_30d', models.BooleanField(default=False)),
                ('readmission_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
            ],
            options={
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('alive', models.BooleanField(default=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('recurrence', models.BooleanField(default=False)),
                ('recurrence_date', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(blank=True, choices=[('local', 'Local recurrence'), ('distant', 'Distant metastasis'), ('both', 'Local and distant')], max_length=20)),
                ('recurrence_site', models.TextField(blank=True, help_text='Specify location of recurrence/metastasis')),
                ('ecog_status', models.IntegerField(blank=True, choices=[(0, 'Fully active, able to carry on all pre-disease performance without restriction'), (1, 'Restricted in physically strenuous activity but ambulatory and able to carry out work'), (2, 'Ambulatory and capable of all self-care but unable to carry out any work activities'), (3, 'Capable of only limited self-care, confined to bed or chair >50% of waking hours'), (4, 'Completely disabled, cannot carry on any self-care, totally confined to bed or chair')], null=True)),
                ('ca19_9', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('cea', models.FloatField(blank=True, help_text='ng/mL', null=True)),
                ('afp', models.FloatField(blank=True, help_text='ng/mL', null=True)),
                ('salvage_surgery', models.BooleanField(default=False)),
                ('salvage_chemotherapy', models.BooleanField(default=False)),
                ('salvage_radiotherapy', models.BooleanField(default=False)),
                ('clinical_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['-followup_date'],
            },
        ),
        migrations.CreateModel(
            name='ChemotherapyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('folfox', 'FOLFOX (Oxaliplatin, 5-FU, Leucovorin)'), ('folfiri', 'FOLFIRI (Irinotecan, 5-FU, Leucovorin)'), ('gemcitabine', 'Gemcitabine monotherapy'), ('gemcitabine_capecitabine', 'Gemcitabine + Capecitabine'), ('folfirinox', 'FOLFIRINOX (5-FU, Leucovorin, Irinotecan, Oxaliplatin)'), ('capecitabine', 'Capecitabine monotherapy'), ('sorafenib', 'Sorafenib'), ('other', 'Other protocol')], max_length=50)),
                ('other_protocol_name', models.CharField(blank=True, help_text='If other protocol selected', max_length=100)),
                ('cycles_planned', models.IntegerField()),
                ('cycles_completed', models.IntegerField()),
                ('setting', models.CharField(choices=[('neoadjuvant', 'Neoadjuvant (preoperative)'), ('adjuvant', 'Adjuvant (postoperative)'), ('palliative', 'Palliative'), ('conversion', 'Conversion therapy')], max_length=20)),
                ('neurotoxicity_grade', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Life-threatening')], default=0)),
                ('neutropenia_grade', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Life-threatening')], default=0)),
                ('thrombocytopenia_grade', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Life-threatening')], default=0)),
                ('dose_reduction', models.BooleanField(default=False)),
                ('dose_reduction_reason', models.TextField(blank=True)),
                ('treatment_delayed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemotherapy', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Chemotherapy protocols',
                'ordering': ['-start_date'],
            },
        ),
    ]
