# Generated by Django 4.2.7 on 2026-03-26 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalprocedure',
            name='biliary_resection_subtype',
            field=models.CharField(blank=True, choices=[('cholecystectomy', 'Cholecystectomy'), ('bd_resection', 'Bile Duct Resection'), ('bypass', 'Biliary Bypass')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='liver_resection_subtype',
            field=models.CharField(blank=True, choices=[('hepatectomy_major', 'Major Hepatectomy (≥3 segments)'), ('hepatectomy_minor', 'Minor Hepatectomy (<3 segments)'), ('non_anatomical', 'Non-anatomical Resection'), ('laparoscopic', 'Laparoscopic Resection'), ('ablative', 'Ablative Procedure')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='pancreatic_resection_subtype',
            field=models.CharField(blank=True, choices=[('whipple', 'Whipple'), ('distal', 'Distal Pancreatectomy'), ('central', 'Central Pancreatectomy'), ('total', 'Total Pancreatectomy')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='pringle_cycles',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='surgical_approach',
            field=models.CharField(choices=[('open', 'Open'), ('laparoscopic', 'Laparoscopic'), ('robotic', 'Robotic'), ('converted', 'Converted (Laparoscopic to Open)')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='procedure_type',
            field=models.CharField(choices=[('pancreaticoduodenectomy', 'Pancreaticoduodenectomy (Whipple)'), ('distal_pancreatectomy', 'Distal Pancreatectomy'), ('central_pancreatectomy', 'Central Pancreatectomy'), ('total_pancreatectomy', 'Total Pancreatectomy'), ('hepatectomy_major', 'Major Hepatectomy (≥3 segments)'), ('hepatectomy_minor', 'Minor Hepatectomy (<3 segments)'), ('cholecystectomy', 'Cholecystectomy'), ('bile_duct_resection', 'Bile Duct Resection'), ('liver_transplant', 'Liver Transplantation'), ('liver_resection', 'Liver Resection'), ('pancreatic_resection', 'Pancreatic Resection'), ('biliary_procedure', 'Biliary Procedure'), ('combined', 'Combined Procedure')], default='liver_resection', max_length=50),
        ),
        migrations.CreateModel(
            name='PancreaticResectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancreatectomy_variant', models.CharField(choices=[('standard_whipple', 'Standard Whipple (Pancreaticoduodenectomy)'), ('pylorus_preserving', 'Pylorus-preserving Pancreaticoduodenectomy (PPPD)'), ('distal_pancreatectomy', 'Distal Pancreatectomy'), ('central_pancreatectomy', 'Central Pancreatectomy'), ('total_pancreatectomy', 'Total Pancreatectomy'), ('enucleation', 'Enucleation')], default='standard_whipple', max_length=50)),
                ('tumor_location', models.CharField(choices=[('head', 'Pancreatic Head'), ('uncinate', 'Uncinate Process'), ('neck', 'Pancreatic Neck'), ('body', 'Pancreatic Body'), ('tail', 'Pancreatic Tail'), ('diffuse', 'Diffuse/Multiple')], default='head', max_length=20)),
                ('tumor_size_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pancreatic_duct_dilated', models.BooleanField(default=False)),
                ('pancreatic_duct_size_mm', models.FloatField(blank=True, null=True)),
                ('pancreatic_duct_stent', models.BooleanField(default=False)),
                ('portal_vein_invasion', models.BooleanField(default=False)),
                ('portal_vein_resection', models.BooleanField(default=False)),
                ('portal_vein_reconstruction_type', models.CharField(blank=True, choices=[('primary_repair', 'Primary Repair'), ('patch', 'Patch Repair'), ('interposition_graft', 'Interposition Graft'), ('vein_graft', 'Vein Graft')], max_length=50)),
                ('superior_mesenteric_vein_invasion', models.BooleanField(default=False)),
                ('superior_mesenteric_artery_invasion', models.BooleanField(default=False)),
                ('celiac_axis_invasion', models.BooleanField(default=False)),
                ('hepatic_artery_invasion', models.BooleanField(default=False)),
                ('pancreatic_texture', models.CharField(choices=[('soft', 'Soft'), ('intermediate', 'Intermediate'), ('hard', 'Hard (Fibrotic)')], default='soft', max_length=20)),
                ('anastomosis_type', models.CharField(choices=[('duct_to_mucosa', 'Duct-to-mucosa'), ('invagination', 'Invagination (Dunking)'), ('binding', 'Binding Pancreaticojejunostomy'), ('blumgart', 'Blumgart Anastomosis')], default='duct_to_mucosa', max_length=20)),
                ('pancreatic_jejunostomy', models.BooleanField(default=True)),
                ('pancreatic_gastrostomy', models.BooleanField(default=False)),
                ('external_drain_placed', models.BooleanField(default=True)),
                ('drain_amylase_pod1', models.FloatField(blank=True, help_text='Drain amylase on POD 1 (U/L)', null=True)),
                ('drain_amylase_pod3', models.FloatField(blank=True, help_text='Drain amylase on POD 3 (U/L)', null=True)),
                ('drain_removal_day', models.IntegerField(blank=True, null=True)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pancreatic_details', to='clinical.surgicalprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='LiverResectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resection_type', models.CharField(choices=[('anatomical', 'Anatomical Resection'), ('non_anatomical', 'Non-anatomical (Wedge)'), ('combined', 'Combined Anatomical + Non-anatomical')], default='anatomical', max_length=20)),
                ('segment_1', models.BooleanField(default=False, help_text='Caudate lobe')),
                ('segment_2', models.BooleanField(default=False)),
                ('segment_3', models.BooleanField(default=False)),
                ('segment_4a', models.BooleanField(default=False)),
                ('segment_4b', models.BooleanField(default=False)),
                ('segment_5', models.BooleanField(default=False)),
                ('segment_6', models.BooleanField(default=False)),
                ('segment_7', models.BooleanField(default=False)),
                ('segment_8', models.BooleanField(default=False)),
                ('hepatectomy_type', models.CharField(choices=[('less_than_section', 'Less than one section'), ('left_lateral_sectionectomy', 'Left lateral sectionectomy (Segments 2-3)'), ('left_hepatectomy', 'Left hepatectomy (Segments 2-4)'), ('right_posterior_sectionectomy', 'Right posterior sectionectomy (Segments 6-7)'), ('right_anterior_sectionectomy', 'Right anterior sectionectomy (Segments 5-8)'), ('right_hepatectomy', 'Right hepatectomy (Segments 5-8)'), ('extended_left_hepatectomy', 'Extended left hepatectomy (Segments 2-5,8)'), ('extended_right_hepatectomy', 'Extended right hepatectomy (Segments 4-8)'), ('central_hepatectomy', 'Central hepatectomy (Segments 4,5,8)'), ('trisegmentectomy', 'Trisegmentectomy')], default='less_than_section', max_length=50)),
                ('number_of_segments', models.IntegerField(blank=True, help_text='Total number of Couinaud segments resected', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('number_of_tumors', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('largest_tumor_size_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tumor_volume_cc', models.FloatField(blank=True, help_text='Estimated total tumor volume', null=True)),
                ('margin_status', models.CharField(blank=True, choices=[('r0', 'R0 (Negative margin)'), ('r1', 'R1 (Microscopically positive)'), ('r2', 'R2 (Macroscopically positive)')], max_length=20, null=True)),
                ('margin_distance_mm', models.FloatField(blank=True, help_text='Distance from tumor to resection margin in mm', null=True)),
                ('parenchyma_quality', models.CharField(choices=[('normal', 'Normal'), ('steatosis_mild', 'Steatosis <30%'), ('steatosis_moderate', 'Steatosis 30-60%'), ('steatosis_severe', 'Steatosis >60%'), ('cirrhosis_compensated', 'Cirrhosis - Child-Pugh A'), ('cirrhosis_decompensated', 'Cirrhosis - Child-Pugh B/C'), ('fibrosis', 'Fibrosis without cirrhosis')], default='normal', max_length=50)),
                ('flr_percentage', models.FloatField(blank=True, help_text='Future liver remnant percentage', null=True)),
                ('flr_volume_cc', models.FloatField(blank=True, help_text='Future liver remnant volume in cc', null=True)),
                ('portal_vein_reconstruction', models.BooleanField(default=False)),
                ('hepatic_artery_reconstruction', models.BooleanField(default=False)),
                ('hepatic_vein_reconstruction', models.BooleanField(default=False)),
                ('ivc_resection', models.BooleanField(default=False)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liver_details', to='clinical.surgicalprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='BiliaryProcedureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biliary_procedure', models.CharField(choices=[('cholecystectomy', 'Cholecystectomy'), ('bile_duct_exploration', 'Bile Duct Exploration'), ('choledochojejunostomy', 'Choledochojejunostomy'), ('hepaticojejunostomy', 'Hepaticojejunostomy'), ('bile_duct_resection', 'Bile Duct Resection'), ('hilar_resection', 'Hilar Resection (Klatskin)'), ('transhepatic_drain', 'Transhepatic Drain Placement')], max_length=50)),
                ('bismuth_classification', models.CharField(blank=True, choices=[('type1', 'Type I - Below confluence'), ('type2', 'Type II - At confluence'), ('type3a', 'Type IIIa - Extends to right hepatic duct'), ('type3b', 'Type IIIb - Extends to left hepatic duct'), ('type4', 'Type IV - Multifocal/involving both sides')], max_length=10, null=True)),
                ('bile_duct_diameter_mm', models.FloatField(blank=True, null=True)),
                ('bile_duct_stricture', models.BooleanField(default=False)),
                ('stricture_location', models.CharField(blank=True, max_length=100)),
                ('anastomosis_level', models.CharField(blank=True, choices=[('infrahilar', 'Infrahilar'), ('hilar', 'Hilar'), ('suprahilar', 'Suprahilar'), ('intrahepatic', 'Intrahepatic')], max_length=50)),
                ('number_of_anastomoses', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preoperative_stent', models.BooleanField(default=False)),
                ('preoperative_stent_type', models.CharField(blank=True, choices=[('plastic', 'Plastic Stent'), ('metal', 'Metal Stent'), ('both', 'Both')], max_length=50)),
                ('postoperative_stent', models.BooleanField(default=False)),
                ('bile_leak_management', models.TextField(blank=True, help_text='How was bile leak managed?')),
                ('ercp_performed', models.BooleanField(default=False)),
                ('ptbd_performed', models.BooleanField(default=False)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biliary_details', to='clinical.surgicalprocedure')),
            ],
        ),
    ]
