# Generated by Django 4.2.7 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_surgicalprocedure_biliary_resection_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='procedure_type',
            field=models.CharField(choices=[('liver_resection', 'Liver Resection'), ('pancreatic_resection', 'Pancreatic Resection'), ('biliary_procedure', 'Biliary Procedure'), ('combined', 'Combined Procedure')], default='liver_resection', max_length=50),
        ),
    ]
