# Generated by Django 4.2.7 on 2026-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_surgicalprocedure_procedure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='clavien_dindo_grade',
            field=models.IntegerField(blank=True, choices=[(0, 'No complication'), (1, 'Grade I - Any deviation from normal course'), (2, 'Grade II - Pharmacologic treatment'), (3, 'Grade IIIa - Intervention without general anesthesia'), (4, 'Grade IIIb - Intervention with general anesthesia'), (5, 'Grade IVa - Single organ dysfunction'), (6, 'Grade IVb - Multiorgan dysfunction'), (7, 'Grade V - Death')], null=True),
        ),
    ]
