# Generated by Django 6.0.3 on 2026-03-28 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_surgicalprocedure_clavien_dindo_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liverresectiondetail',
            name='number_of_tumors',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='biliary_resection_subtype',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='liver_resection_subtype',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='pancreatic_resection_subtype',
        ),
        migrations.AddField(
            model_name='liverresectiondetail',
            name='total_tumor_count',
            field=models.IntegerField(default=0, help_text='Auto-calculated from individual tumors'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='biliary_surgery_subtype',
            field=models.CharField(blank=True, choices=[('cholecystectomy', 'Cholecystectomy'), ('bd_resection', 'Bile Duct Resection'), ('bypass', 'Biliary Bypass'), ('hepaticojejunostomy', 'Hepaticojejunostomy'), ('choledochojejunostomy', 'Choledochojejunostomy'), ('stent_placement', 'Stent Placement'), ('ptbd', 'PTBD - Percutaneous Transhepatic Biliary Drainage'), ('ercp', 'ERCP')], default='', max_length=50, verbose_name='Biliary Surgery Subtype'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='liver_surgery_subtype',
            field=models.CharField(blank=True, choices=[('hepatectomy_major', 'Major Hepatectomy (≥3 segments)'), ('hepatectomy_minor', 'Minor Hepatectomy (<3 segments)'), ('non_anatomical', 'Non-anatomical Resection'), ('ablative', 'Ablative Procedure'), ('fenestration', 'Fenestration (for cysts)'), ('deroofing', 'Deroofing'), ('biopsy', 'Liver Biopsy'), ('liver_transplant', 'Liver Transplantation')], default='', max_length=50, verbose_name='Liver Surgery Subtype'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='pancreatic_surgery_subtype',
            field=models.CharField(blank=True, choices=[('whipple', 'Whipple Procedure (Pancreaticoduodenectomy)'), ('distal', 'Distal Pancreatectomy'), ('central', 'Central Pancreatectomy'), ('total', 'Total Pancreatectomy'), ('enucleation', 'Enucleation'), ('drainage', 'Drainage Procedure (Puestow, Frey)'), ('necrosectomy', 'Necrosectomy'), ('cystogastrostomy', 'Cystogastrostomy'), ('biopsy', 'Pancreatic Biopsy')], default='', max_length=50, verbose_name='Pancreatic Surgery Subtype'),
        ),
        migrations.AlterField(
            model_name='liverresectiondetail',
            name='largest_tumor_size_cm',
            field=models.FloatField(blank=True, help_text='Auto-calculated from individual tumors', null=True),
        ),
        migrations.AlterField(
            model_name='liverresectiondetail',
            name='total_tumor_volume_cc',
            field=models.FloatField(blank=True, help_text='Auto-calculated from individual tumors', null=True),
        ),
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='procedure_type',
            field=models.CharField(choices=[('liver_surgery', 'Liver Surgery'), ('pancreatic_surgery', 'Pancreatic Surgery'), ('biliary_surgery', 'Biliary Surgery'), ('combined', 'Combined Procedure')], default='liver_surgery', max_length=50),
        ),
        migrations.CreateModel(
            name='LiverTumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('S1', 'Segment I - Caudate lobe'), ('S2', 'Segment II'), ('S3', 'Segment III'), ('S4a', 'Segment IVa'), ('S4b', 'Segment IVb'), ('S5', 'Segment V'), ('S6', 'Segment VI'), ('S7', 'Segment VII'), ('S8', 'Segment VIII'), ('multiple', 'Multiple segments involved')], help_text='Couinaud segment', max_length=10)),
                ('segment_details', models.CharField(blank=True, help_text='If multiple segments, specify', max_length=100)),
                ('size_cm', models.FloatField(help_text='Largest dimension in cm', validators=[django.core.validators.MinValueValidator(0)])),
                ('size_other_dimensions', models.CharField(blank=True, help_text='e.g., 3.2 x 2.8 x 2.1 cm', max_length=50)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary tumor vs metastasis')),
                ('differentiation', models.CharField(blank=True, choices=[('well', 'Well differentiated (Grade 1)'), ('moderate', 'Moderately differentiated (Grade 2)'), ('poor', 'Poorly differentiated (Grade 3)'), ('undifferentiated', 'Undifferentiated (Grade 4)'), ('unknown', 'Unknown')], max_length=20)),
                ('microvascular_invasion', models.BooleanField(default=False)),
                ('macrovascular_invasion', models.BooleanField(default=False)),
                ('necrosis_percentage', models.IntegerField(blank=True, help_text='Percentage of tumor necrosis (after neoadjuvant therapy)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('liver_resection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumors', to='clinical.liverresectiondetail')),
            ],
            options={
                'ordering': ['segment'],
            },
        ),
    ]
