# Generated by Django 6.0.3 on 2026-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_update_surgery_subtype_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='biliary_surgery_subtype',
            field=models.CharField(blank=True, choices=[('cholecystectomy', 'Cholecystectomy'), ('bd_resection', 'Bile Duct Resection'), ('bypass', 'Biliary Bypass'), ('hepaticojejunostomy', 'Hepaticojejunostomy'), ('choledochojejunostomy', 'Choledochojejunostomy'), ('stent_placement', 'Stent Placement'), ('ptbd', 'PTBD - Percutaneous Transhepatic Biliary Drainage'), ('ercp', 'ERCP')], default='', max_length=50, verbose_name='Biliary Surgery Subtype'),
        ),
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='liver_surgery_subtype',
            field=models.CharField(blank=True, choices=[('hepatectomy_major', 'Major Hepatectomy (≥3 segments)'), ('hepatectomy_minor', 'Minor Hepatectomy (<3 segments)'), ('non_anatomical', 'Non-anatomical Resection'), ('ablative', 'Ablative Procedure'), ('fenestration', 'Fenestration (for cysts)'), ('deroofing', 'Deroofing'), ('biopsy', 'Liver Biopsy'), ('liver_transplant', 'Liver Transplantation')], default='', max_length=50, verbose_name='Liver Surgery Subtype'),
        ),
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='pancreatic_surgery_subtype',
            field=models.CharField(blank=True, choices=[('whipple', 'Whipple Procedure (Pancreaticoduodenectomy)'), ('distal', 'Distal Pancreatectomy'), ('central', 'Central Pancreatectomy'), ('total', 'Total Pancreatectomy'), ('enucleation', 'Enucleation'), ('drainage', 'Drainage Procedure (Puestow, Frey)'), ('necrosectomy', 'Necrosectomy'), ('cystogastrostomy', 'Cystogastrostomy'), ('biopsy', 'Pancreatic Biopsy')], default='', max_length=50, verbose_name='Pancreatic Surgery Subtype'),
        ),
    ]
