# Generated by Django 6.0.3 on 2026-03-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_surgicalprocedure_biliary_surgery_subtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='bile_leak',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='bile_leak_grade',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='bile_leak_treatment',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='popf_drain_amylase',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='popf_grade',
        ),
        migrations.RemoveField(
            model_name='surgicalprocedure',
            name='popf_present',
        ),
    ]
