# Generated by Django 6.0.3 on 2026-03-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_remove_surgicalprocedure_bile_leak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='disease_free_survival_months',
            field=models.FloatField(blank=True, help_text='Months until recurrence or death', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='last_known_alive_date',
            field=models.DateField(blank=True, help_text='Date patient was last confirmed alive', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='overall_survival_months',
            field=models.FloatField(blank=True, help_text='Months from surgery to death or last follow-up', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='recurrence_free_survival_months',
            field=models.FloatField(blank=True, help_text='Months from surgery to recurrence', null=True),
        ),
        migrations.CreateModel(
            name='TextbookOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_major_complications', models.BooleanField(default=False, help_text='No Clavien-Dindo ≥ III complications')),
                ('no_prolonged_los', models.BooleanField(default=False, help_text='Length of stay ≤ 75th percentile for procedure')),
                ('no_readmission', models.BooleanField(default=False, help_text='No 30-day readmission')),
                ('no_mortality', models.BooleanField(default=False, help_text='No 30-day mortality')),
                ('negative_margins', models.BooleanField(default=False, help_text='R0 resection')),
                ('adequate_lymph_node_yield', models.BooleanField(default=False, help_text='≥12 lymph nodes examined')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_outcome', to='clinical.surgicalprocedure')),
            ],
            options={
                'verbose_name': 'Textbook Outcome',
                'verbose_name_plural': 'Textbook Outcomes',
            },
        ),
    ]
