# Generated by Django 6.0.3 on 2026-04-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_followup_created_at_followup_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarcopeniaAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeletal_muscle_index_cm2_m2', models.FloatField(blank=True, help_text='Skeletal muscle index at L3 (cm²/m²) - Sarcopenia cutoff: M<55, F<39', null=True)),
                ('psoas_muscle_area_cm2', models.FloatField(blank=True, help_text='Psoas muscle area at L3 (cm²)', null=True)),
                ('visceral_fat_area_cm2', models.FloatField(blank=True, help_text='Visceral fat area at L3 (cm²)', null=True)),
                ('subcutaneous_fat_area_cm2', models.FloatField(blank=True, help_text='Subcutaneous fat area at L3 (cm²)', null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Patient gender for cutoff determination', max_length=1)),
                ('is_sarcopenic', models.BooleanField(default=False, help_text='Based on SMI cutoffs: Male <55 cm²/m², Female <39 cm²/m²')),
                ('ct_slice_location', models.CharField(blank=True, help_text='CT slice location (e.g., L3 vertebra)', max_length=50)),
                ('ct_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surgical_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarcopenia_assessments', to='clinical.surgicalprocedure')),
            ],
            options={
                'verbose_name_plural': 'Sarcopenia Assessments',
                'ordering': ['-ct_date'],
            },
        ),
    ]
