# Generated by Django 6.0.3 on 2026-04-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_sarcopeniaassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SarcopeniaAssessment',
        ),
    ]
