# Generated by Django 6.0.3 on 2026-04-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_delete_sarcopeniaassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalprocedure',
            name='anesthesiologist',
            field=models.ForeignKey(blank=True, help_text='Primary anesthesiologist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='assistant_surgeon_1',
            field=models.ForeignKey(blank=True, help_text='First assistant surgeon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant1_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='assistant_surgeon_2',
            field=models.ForeignKey(blank=True, help_text='Second assistant surgeon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant2_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='conversion_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='conversion_to_open',
            field=models.BooleanField(default=False, help_text='If laparoscopic/robotic, was conversion to open required?'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='date_of_death_if_known',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='days_from_neoadjuvant_to_surgery',
            field=models.IntegerField(blank=True, help_text='Days between last neoadjuvant treatment and surgery', null=True),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='enhanced_recovery_protocol',
            field=models.BooleanField(default=False, help_text='Was enhanced recovery protocol (ERP/ERAS) used?'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='indication',
            field=models.CharField(choices=[('malignancy', 'Malignancy (confirmed)'), ('suspected_malignancy', 'Suspected Malignancy'), ('benign', 'Benign Disease'), ('trauma', 'Trauma'), ('infection', 'Infection/Abscess'), ('other', 'Other')], default='malignancy', max_length=30),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='indication_other',
            field=models.CharField(blank=True, help_text='If other indication', max_length=200),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='intraoperative_complications',
            field=models.TextField(blank=True, help_text='Describe any intraoperative complications (e.g., bleeding, hypotension, arrhythmia)'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='mortality_30d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='mortality_90d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='mortality_in_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='neoadjuvant_chemoradiation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='neoadjuvant_chemotherapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='neoadjuvant_protocol',
            field=models.CharField(blank=True, help_text='e.g., FOLFIRINOX, GEMCITABINE', max_length=200),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='neoadjuvant_radiotherapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='operative_report_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='operative_report_link',
            field=models.URLField(blank=True, help_text='Link to scanned operative report'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='primary_surgeon',
            field=models.ForeignKey(blank=True, help_text='Main operating surgeon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_surgeon_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='readmission_90d',
            field=models.BooleanField(default=False, help_text='90-day readmission'),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='supervising_surgeon',
            field=models.ForeignKey(blank=True, help_text='Attending surgeon supervising the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalprocedure',
            name='urgency',
            field=models.CharField(choices=[('elective', 'Elective - Scheduled in advance'), ('urgent', 'Urgent - Within 24-48 hours'), ('emergency', 'Emergency - Immediate (<24 hours)')], default='elective', max_length=20),
        ),
    ]
