# Generated by Django 4.2.7 on 2026-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_code', models.CharField(help_text='ICD-10 code (e.g., C22.0)', max_length=10, unique=True)),
                ('diagnosis_name', models.CharField(help_text='Diagnosis name', max_length=200)),
                ('category', models.CharField(choices=[('liver_malignant', 'Liver - Malignant'), ('liver_benign', 'Liver - Benign'), ('pancreas_malignant', 'Pancreas - Malignant'), ('pancreas_benign', 'Pancreas - Benign'), ('biliary_malignant', 'Biliary - Malignant'), ('biliary_benign', 'Biliary - Benign'), ('other', 'Other')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['category', 'diagnosis_name'],
            },
        ),
        migrations.CreateModel(
            name='HistologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Histology type name', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('malignant', 'Malignant'), ('benign', 'Benign'), ('premalignant', 'Premalignant')], max_length=50)),
                ('organ_system', models.CharField(choices=[('liver', 'Liver'), ('pancreas', 'Pancreas'), ('biliary', 'Biliary'), ('general', 'General')], default='general', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Histology Types',
                'ordering': ['category', 'name'],
            },
        ),
    ]
