# Generated by Django 4.2.7 on 2026-03-26 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('specimen_type', models.CharField(choices=[('liver_resection', 'Liver Resection'), ('pancreatic_resection', 'Pancreatic Resection'), ('bile_duct_resection', 'Bile Duct Resection'), ('gallbladder', 'Gallbladder'), ('biopsy_liver', 'Liver Biopsy'), ('biopsy_pancreas', 'Pancreas Biopsy'), ('biopsy_lymph_node', 'Lymph Node Biopsy'), ('biopsy_peritoneal', 'Peritoneal Biopsy')], max_length=50)),
                ('diagnosis', models.TextField()),
                ('histological_type', models.CharField(help_text='e.g., Pancreatic ductal adenocarcinoma, Hepatocellular carcinoma', max_length=200)),
                ('tumor_size_cm', models.FloatField(help_text='Largest tumor dimension in cm', validators=[django.core.validators.MinValueValidator(0)])),
                ('tumor_size_other_dimensions', models.CharField(blank=True, help_text='e.g., 3.2 x 2.8 x 2.1 cm', max_length=100)),
                ('number_of_tumors', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('differentiation', models.CharField(choices=[('well', 'Well differentiated (Grade 1)'), ('moderate', 'Moderately differentiated (Grade 2)'), ('poor', 'Poorly differentiated (Grade 3)'), ('undifferentiated', 'Undifferentiated (Grade 4)')], max_length=20)),
                ('hcc_subtype', models.CharField(blank=True, choices=[('classic', 'Classic'), ('fibrolamellar', 'Fibrolamellar'), ('scirrhous', 'Scirrhous'), ('sarcomatoid', 'Sarcomatoid')], max_length=100)),
                ('pancreatic_subtype', models.CharField(blank=True, choices=[('pdac', 'Pancreatic Ductal Adenocarcinoma'), ('acinar', 'Acinar Cell Carcinoma'), ('neuroendocrine', 'Neuroendocrine Tumor'), ('ipmn', 'Intraductal Papillary Mucinous Neoplasm'), ('mcn', 'Mucinous Cystic Neoplasm'), ('spn', 'Solid Pseudopapillary Neoplasm')], max_length=100)),
                ('biliary_subtype', models.CharField(blank=True, choices=[('intrahepatic', 'Intrahepatic Cholangiocarcinoma'), ('perihilar', 'Perihilar Cholangiocarcinoma (Klatskin)'), ('distal', 'Distal Cholangiocarcinoma'), ('gallbladder', 'Gallbladder Carcinoma')], max_length=100)),
                ('margin_status', models.CharField(choices=[('r0', 'R0 (Negative margin)'), ('r1', 'R1 (Microscopically positive)'), ('r2', 'R2 (Macroscopically positive)'), ('rx', 'RX (Margin cannot be assessed)')], max_length=10)),
                ('margin_distance_mm', models.FloatField(blank=True, help_text='Distance from tumor to closest margin in mm', null=True)),
                ('closest_margin', models.CharField(blank=True, help_text='e.g., Parenchymal, Bile duct, Vascular', max_length=100)),
                ('microvascular_invasion', models.BooleanField(default=False)),
                ('macrovascular_invasion', models.BooleanField(default=False)),
                ('vascular_invasion_details', models.TextField(blank=True, help_text='Specify vessels involved')),
                ('lymph_nodes_examined', models.IntegerField(default=0)),
                ('lymph_nodes_positive', models.IntegerField(default=0)),
                ('lymph_node_ratio', models.FloatField(blank=True, help_text='Positive/Examined ratio', null=True)),
                ('lymph_node_stations', models.TextField(blank=True, help_text='Stations with positive nodes')),
                ('perineural_invasion', models.BooleanField(default=False)),
                ('peritoneal_invasion', models.BooleanField(default=False)),
                ('t_stage', models.CharField(blank=True, choices=[('Tis', 'Tis - Carcinoma in situ'), ('T1', 'T1 - Tumor ≤2 cm'), ('T1a', 'T1a - Tumor ≤2 cm, single'), ('T1b', 'T1b - Tumor >2 cm, single'), ('T1c', 'T1c - Tumor >2 cm, single with vascular invasion'), ('T2', 'T2 - Multiple tumors, ≤5 cm'), ('T3', 'T3 - Multiple tumors, >5 cm or portal vein invasion'), ('T4', 'T4 - Tumor invades adjacent organs or perforates visceral peritoneum')], max_length=10)),
                ('n_stage', models.CharField(blank=True, choices=[('N0', 'N0 - No regional lymph node metastasis'), ('N1', 'N1 - Regional lymph node metastasis')], max_length=10)),
                ('m_stage', models.CharField(blank=True, choices=[('M0', 'M0 - No distant metastasis'), ('M1', 'M1 - Distant metastasis')], max_length=10)),
                ('background_liver', models.TextField(blank=True, help_text='e.g., Cirrhosis, Steatosis, Hepatitis')),
                ('fibrosis_score', models.IntegerField(blank=True, choices=[(0, 'F0 - No fibrosis'), (1, 'F1 - Portal fibrosis'), (2, 'F2 - Periportal fibrosis'), (3, 'F3 - Bridging fibrosis'), (4, 'F4 - Cirrhosis')], null=True)),
                ('steatosis_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pancreatic_parenchyma', models.TextField(blank=True, help_text='e.g., Chronic pancreatitis, IPMN, MCN')),
                ('pancreatic_intraepithelial_neoplasia', models.CharField(blank=True, choices=[('none', 'None'), ('panin_1', 'PanIN-1'), ('panin_2', 'PanIN-2'), ('panin_3', 'PanIN-3')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MolecularMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kras_mutation', models.BooleanField(default=False)),
                ('kras_mutation_type', models.CharField(blank=True, choices=[('G12D', 'G12D'), ('G12V', 'G12V'), ('G12R', 'G12R'), ('G12C', 'G12C'), ('G13D', 'G13D'), ('Q61H', 'Q61H')], max_length=50)),
                ('egfr_expression', models.CharField(blank=True, choices=[('negative', 'Negative'), ('weak', 'Weak (1+)'), ('moderate', 'Moderate (2+)'), ('strong', 'Strong (3+)')], max_length=20)),
                ('her2_status', models.CharField(blank=True, choices=[('negative', 'Negative'), ('equivocal', 'Equivocal'), ('positive', 'Positive')], max_length=20)),
                ('msi_status', models.CharField(blank=True, choices=[('msi_h', 'MSI-High'), ('msi_l', 'MSI-Low'), ('mss', 'MSS (Microsatellite Stable)')], max_length=20)),
                ('mlh1', models.CharField(blank=True, max_length=20)),
                ('msh2', models.CharField(blank=True, max_length=20)),
                ('msh6', models.CharField(blank=True, max_length=20)),
                ('pms2', models.CharField(blank=True, max_length=20)),
                ('p53_status', models.CharField(blank=True, choices=[('wildtype', 'Wildtype'), ('mutated', 'Mutated'), ('overexpressed', 'Overexpressed')], max_length=20)),
                ('smad4_status', models.CharField(blank=True, choices=[('intact', 'Intact'), ('lost', 'Lost')], max_length=20)),
                ('ngs_performed', models.BooleanField(default=False)),
                ('ngs_findings', models.TextField(blank=True, help_text='List all mutations found')),
                ('comments', models.TextField(blank=True)),
                ('pathology_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='molecular_markers', to='pathology.pathologyreport')),
            ],
        ),
    ]
