# Generated by Django 4.2.7 on 2026-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologyreport',
            name='biliary_subtype',
        ),
        migrations.RemoveField(
            model_name='pathologyreport',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='pathologyreport',
            name='hcc_subtype',
        ),
        migrations.RemoveField(
            model_name='pathologyreport',
            name='histological_type',
        ),
        migrations.RemoveField(
            model_name='pathologyreport',
            name='pancreatic_subtype',
        ),
        migrations.AddField(
            model_name='pathologyreport',
            name='diagnosis_notes',
            field=models.TextField(blank=True, help_text='Additional diagnostic notes if needed'),
        ),
        migrations.AddField(
            model_name='pathologyreport',
            name='histological_type_other',
            field=models.CharField(blank=True, help_text='If other histology type', max_length=200),
        ),
        migrations.AlterField(
            model_name='pathologyreport',
            name='differentiation',
            field=models.CharField(blank=True, choices=[('well', 'Well differentiated (Grade 1)'), ('moderate', 'Moderately differentiated (Grade 2)'), ('poor', 'Poorly differentiated (Grade 3)'), ('undifferentiated', 'Undifferentiated (Grade 4)')], max_length=20, null=True),
        ),
    ]
