# Generated by Django 4.2.7 on 2026-03-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0001_initial'),
        ('pathology', '0002_remove_pathologyreport_biliary_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologyreport',
            name='diagnosis',
            field=models.ForeignKey(blank=True, help_text='ICD-10 diagnosis code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_reports', to='medical_codes.diagnosis'),
        ),
        migrations.AddField(
            model_name='pathologyreport',
            name='histological_type',
            field=models.ForeignKey(blank=True, help_text='Histological type from standardized list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_reports', to='medical_codes.histologytype'),
        ),
    ]
