# Generated by Django 4.2.7 on 2026-03-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumorMarkerPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('timing', models.CharField(choices=[('baseline', 'Baseline (Pre-treatment)'), ('during_treatment', 'During Treatment'), ('post_treatment', 'Post-treatment'), ('follow_up', 'Follow-up'), ('recurrence', 'At Recurrence')], max_length=20)),
                ('ca19_9', models.FloatField(blank=True, help_text='U/mL (Carbohydrate antigen 19-9)', null=True)),
                ('ca19_9_upper_limit', models.FloatField(blank=True, help_text='Upper limit of normal', null=True)),
                ('cea', models.FloatField(blank=True, help_text='ng/mL (Carcinoembryonic antigen)', null=True)),
                ('cea_upper_limit', models.FloatField(blank=True, help_text='Upper limit of normal', null=True)),
                ('afp', models.FloatField(blank=True, help_text='ng/mL (Alpha-fetoprotein)', null=True)),
                ('afp_upper_limit', models.FloatField(blank=True, help_text='Upper limit of normal (usually <10)', null=True)),
                ('chromogranin_a', models.FloatField(blank=True, help_text='ng/mL (CgA)', null=True)),
                ('chromogranin_a_upper_limit', models.FloatField(blank=True, null=True)),
                ('neuron_specific_enolase', models.FloatField(blank=True, help_text='ng/mL (NSE)', null=True)),
                ('nse_upper_limit', models.FloatField(blank=True, null=True)),
                ('pancreastatin', models.FloatField(blank=True, help_text='pg/mL', null=True)),
                ('serotonin', models.FloatField(blank=True, help_text='nmol/L', null=True)),
                ('hiaa_5', models.FloatField(blank=True, help_text='μmol/24h (5-HIAA in urine)', null=True)),
                ('ca_50', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('ca_242', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('ca_125', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('ca_15_3', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('ca_72_4', models.FloatField(blank=True, help_text='U/mL', null=True)),
                ('des_gamma_carboxy_prothrombin', models.FloatField(blank=True, help_text='mAU/mL (DCP)', null=True)),
                ('golgi_protein_73', models.FloatField(blank=True, help_text='ng/mL (GP73)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about marker results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_markers', to='patients.patient')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='MicrobiologyCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood Culture'), ('drain_fluid', 'Drain Fluid'), ('bile', 'Bile'), ('wound', 'Wound Swab'), ('urine', 'Urine'), ('sputum', 'Sputum'), ('peritoneal_fluid', 'Peritoneal Fluid')], max_length=20)),
                ('organism', models.CharField(help_text='Microorganism identified', max_length=200)),
                ('antibiotic_sensitivity', models.TextField(blank=True, help_text='List sensitive antibiotics')),
                ('resistant_antibiotics', models.TextField(blank=True, help_text='List resistant antibiotics')),
                ('clinical_significance', models.BooleanField(default=True, help_text='Considered clinically significant?')),
                ('infection_site', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField(blank=True, null=True)),
                ('timing', models.CharField(choices=[('preoperative', 'Preoperative'), ('postoperative_day1', 'Postoperative Day 1'), ('postoperative_day3', 'Postoperative Day 3'), ('postoperative_day5', 'Postoperative Day 5'), ('postoperative_day7', 'Postoperative Day 7'), ('pre_chemotherapy', 'Pre-chemotherapy'), ('post_chemotherapy', 'Post-chemotherapy'), ('follow_up', 'Follow-up')], max_length=30)),
                ('hemoglobin', models.FloatField(blank=True, help_text='g/L', null=True)),
                ('hematocrit', models.FloatField(blank=True, help_text='%', null=True)),
                ('wbc', models.FloatField(blank=True, help_text='x10^9/L', null=True)),
                ('neutrophils', models.FloatField(blank=True, help_text='x10^9/L', null=True)),
                ('lymphocytes', models.FloatField(blank=True, help_text='x10^9/L', null=True)),
                ('monocytes', models.FloatField(blank=True, help_text='x10^9/L', null=True)),
                ('platelets', models.FloatField(blank=True, help_text='x10^9/L', null=True)),
                ('alt', models.FloatField(blank=True, help_text='U/L (Alanine aminotransferase)', null=True)),
                ('ast', models.FloatField(blank=True, help_text='U/L (Aspartate aminotransferase)', null=True)),
                ('alp', models.FloatField(blank=True, help_text='U/L (Alkaline phosphatase)', null=True)),
                ('ggt', models.FloatField(blank=True, help_text='U/L (Gamma-glutamyl transferase)', null=True)),
                ('total_bilirubin', models.FloatField(blank=True, help_text='μmol/L', null=True)),
                ('direct_bilirubin', models.FloatField(blank=True, help_text='μmol/L', null=True)),
                ('indirect_bilirubin', models.FloatField(blank=True, help_text='μmol/L', null=True)),
                ('total_protein', models.FloatField(blank=True, help_text='g/L', null=True)),
                ('albumin', models.FloatField(blank=True, help_text='g/L', null=True)),
                ('inr', models.FloatField(blank=True, null=True)),
                ('pt', models.FloatField(blank=True, help_text='seconds (Prothrombin time)', null=True)),
                ('ptt', models.FloatField(blank=True, help_text='seconds (Partial thromboplastin time)', null=True)),
                ('creatinine', models.FloatField(blank=True, help_text='μmol/L', null=True)),
                ('urea', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('egfr', models.FloatField(blank=True, help_text='mL/min/1.73m² (eGFR)', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('potassium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('chloride', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('calcium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('magnesium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('phosphate', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('crp', models.FloatField(blank=True, help_text='mg/L (C-reactive protein)', null=True)),
                ('esr', models.FloatField(blank=True, help_text='mm/h (Erythrocyte sedimentation rate)', null=True)),
                ('procalcitonin', models.FloatField(blank=True, help_text='ng/mL', null=True)),
                ('prealbumin', models.FloatField(blank=True, help_text='mg/L', null=True)),
                ('transferrin', models.FloatField(blank=True, help_text='g/L', null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_panels', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Laboratory panels',
                'ordering': ['-collection_date'],
            },
        ),
    ]
