# Generated by Django 6.0.3 on 2026-03-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumormarkerpanel',
            name='afp_upper_limit',
        ),
        migrations.RemoveField(
            model_name='tumormarkerpanel',
            name='ca19_9_upper_limit',
        ),
        migrations.RemoveField(
            model_name='tumormarkerpanel',
            name='cea_upper_limit',
        ),
        migrations.RemoveField(
            model_name='tumormarkerpanel',
            name='chromogranin_a_upper_limit',
        ),
        migrations.RemoveField(
            model_name='tumormarkerpanel',
            name='nse_upper_limit',
        ),
    ]
