# Generated by Django 4.2.7 on 2026-03-25 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MELDScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('bilirubin', models.FloatField(help_text='μmol/L', validators=[django.core.validators.MinValueValidator(0)])),
                ('inr', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creatinine', models.FloatField(help_text='μmol/L', validators=[django.core.validators.MinValueValidator(0)])),
                ('dialysis', models.BooleanField(default=False)),
                ('sodium', models.FloatField(blank=True, help_text='mmol/L (for MELD-Na)', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meld_scores', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_assessed'],
            },
        ),
        migrations.CreateModel(
            name='ChildPughScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('bilirubin', models.FloatField(help_text='μmol/L')),
                ('albumin', models.FloatField(help_text='g/L')),
                ('inr', models.FloatField()),
                ('ascites', models.CharField(choices=[('none', 'None'), ('mild', 'Mild (diuretic responsive)'), ('moderate', 'Moderate/Severe (diuretic refractory)')], max_length=20)),
                ('encephalopathy', models.CharField(choices=[('none', 'None'), ('grade1_2', 'Grade I-II (mild)'), ('grade3_4', 'Grade III-IV (severe)')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_pugh_scores', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CharlsonComorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('myocardial_infarction', models.BooleanField(default=False)),
                ('congestive_heart_failure', models.BooleanField(default=False)),
                ('peripheral_vascular_disease', models.BooleanField(default=False)),
                ('cerebrovascular_disease', models.BooleanField(default=False)),
                ('dementia', models.BooleanField(default=False)),
                ('chronic_pulmonary_disease', models.BooleanField(default=False)),
                ('connective_tissue_disease', models.BooleanField(default=False)),
                ('peptic_ulcer_disease', models.BooleanField(default=False)),
                ('mild_liver_disease', models.BooleanField(default=False)),
                ('moderate_severe_liver_disease', models.BooleanField(default=False)),
                ('diabetes_without_complications', models.BooleanField(default=False)),
                ('diabetes_with_complications', models.BooleanField(default=False)),
                ('hemiplegia', models.BooleanField(default=False)),
                ('moderate_severe_kidney_disease', models.BooleanField(default=False)),
                ('solid_tumor', models.BooleanField(default=False, help_text='Non-metastatic solid tumor')),
                ('leukemia', models.BooleanField(default=False)),
                ('lymphoma', models.BooleanField(default=False)),
                ('metastatic_solid_tumor', models.BooleanField(default=False)),
                ('aids', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charlson_scores', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ASAScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('asa_class', models.IntegerField(choices=[(1, 'ASA I - Healthy patient'), (2, 'ASA II - Mild systemic disease'), (3, 'ASA III - Severe systemic disease'), (4, 'ASA IV - Severe systemic disease that is constant threat to life'), (5, 'ASA V - Moribund patient'), (6, 'ASA VI - Brain-dead organ donor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('emergency', models.BooleanField(default=False, help_text='Emergency surgery?')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asa_scores', to='patients.patient')),
            ],
        ),
    ]
