# Generated by Django 4.2.7 on 2026-03-25 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpughscore',
            name='albumin',
            field=models.FloatField(blank=True, help_text='g/L', null=True),
        ),
        migrations.AlterField(
            model_name='childpughscore',
            name='ascites',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild (diuretic responsive)'), ('moderate', 'Moderate/Severe (diuretic refractory)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='childpughscore',
            name='bilirubin',
            field=models.FloatField(blank=True, help_text='μmol/L', null=True),
        ),
        migrations.AlterField(
            model_name='childpughscore',
            name='encephalopathy',
            field=models.CharField(choices=[('none', 'None'), ('grade1_2', 'Grade I-II (mild)'), ('grade3_4', 'Grade III-IV (severe)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='childpughscore',
            name='inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meldscore',
            name='bilirubin',
            field=models.FloatField(blank=True, help_text='μmol/L', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meldscore',
            name='creatinine',
            field=models.FloatField(blank=True, help_text='μmol/L', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meldscore',
            name='inr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
