# Generated by Django 6.0.3 on 2026-04-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_tumormarkerpanel_afp_upper_limit_and_more'),
        ('patients', '0005_remove_patient_last_followup_date'),
        ('scoring', '0002_alter_childpughscore_albumin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibrosisScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('fib4_score', models.FloatField(blank=True, help_text='FIB-4 score', null=True)),
                ('apri_score', models.FloatField(blank=True, help_text='APRI score', null=True)),
                ('fib4_category', models.CharField(blank=True, choices=[('low', 'Low risk of advanced fibrosis (<1.45)'), ('intermediate', 'Intermediate risk (1.45-3.25)'), ('high', 'High risk of advanced fibrosis (>3.25)')], max_length=20, null=True)),
                ('apri_category', models.CharField(blank=True, choices=[('low', 'Low risk of cirrhosis (<0.5)'), ('intermediate', 'Intermediate risk (0.5-1.5)'), ('high', 'High risk of cirrhosis (>1.5)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratorypanel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibrosis_scores', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Fibrosis Scores',
                'ordering': ['-date_assessed'],
            },
        ),
        migrations.CreateModel(
            name='NutritionalRiskIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('albumin_g_l', models.FloatField(help_text='Serum albumin (g/L)')),
                ('usual_weight_kg', models.FloatField(help_text='Usual weight before illness (kg)')),
                ('current_weight_kg', models.FloatField(help_text='Current weight (kg)')),
                ('nri_score', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('severe', 'Severe malnutrition (<83.5)'), ('moderate', 'Moderate malnutrition (83.5-97.5)'), ('mild', 'Mild malnutrition (97.5-100)'), ('normal', 'Normal nutrition (>100)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nri_scores', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Nutritional Risk Indices',
                'ordering': ['-date_assessed'],
            },
        ),
    ]
