# Generated by Django 6.0.3 on 2026-03-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0005_remove_liverresectiondetail_number_of_tumors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_days', models.IntegerField(help_text='Postoperative day of onset (0 for intraoperative)')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_days', models.IntegerField(blank=True, help_text='Postoperative day of resolution', null=True)),
                ('clavien_grade', models.IntegerField(choices=[(1, 'Grade I - Any deviation from normal course without need for treatment'), (2, 'Grade II - Pharmacologic treatment required'), (3, 'Grade IIIa - Intervention without general anesthesia'), (4, 'Grade IIIb - Intervention with general anesthesia'), (5, 'Grade IVa - Single organ dysfunction'), (6, 'Grade IVb - Multiorgan dysfunction'), (7, 'Grade V - Death of patient')])),
                ('treatment', models.TextField(blank=True, help_text='Describe treatment provided')),
                ('reoperation_required', models.BooleanField(default=False)),
                ('reoperation_details', models.TextField(blank=True)),
                ('resolved_completely', models.BooleanField(default=True, help_text='Did the complication resolve completely?')),
                ('sequelae', models.TextField(blank=True, help_text='Any long-term sequelae')),
                ('complication_type', models.CharField(choices=[('surgical_site_infection', 'Surgical Site Infection'), ('pneumonia', 'Pneumonia'), ('uti', 'Urinary Tract Infection'), ('sepsis', 'Sepsis'), ('dvt', 'Deep Vein Thrombosis'), ('pe', 'Pulmonary Embolism'), ('mi', 'Myocardial Infarction'), ('stroke', 'Stroke'), ('aki', 'Acute Kidney Injury'), ('delirium', 'Delirium'), ('ileus', 'Prolonged Ileus (>5 days)'), ('bleeding', 'Postoperative Bleeding requiring transfusion'), ('anastomotic_leak', 'Anastomotic Leak'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Specific details about the complication')),
                ('surgical_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_complications', to='clinical.surgicalprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiverComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_days', models.IntegerField(help_text='Postoperative day of onset (0 for intraoperative)')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_days', models.IntegerField(blank=True, help_text='Postoperative day of resolution', null=True)),
                ('clavien_grade', models.IntegerField(choices=[(1, 'Grade I - Any deviation from normal course without need for treatment'), (2, 'Grade II - Pharmacologic treatment required'), (3, 'Grade IIIa - Intervention without general anesthesia'), (4, 'Grade IIIb - Intervention with general anesthesia'), (5, 'Grade IVa - Single organ dysfunction'), (6, 'Grade IVb - Multiorgan dysfunction'), (7, 'Grade V - Death of patient')])),
                ('treatment', models.TextField(blank=True, help_text='Describe treatment provided')),
                ('reoperation_required', models.BooleanField(default=False)),
                ('reoperation_details', models.TextField(blank=True)),
                ('resolved_completely', models.BooleanField(default=True, help_text='Did the complication resolve completely?')),
                ('sequelae', models.TextField(blank=True, help_text='Any long-term sequelae')),
                ('complication_type', models.CharField(choices=[('bile_leak_grade_a', 'Bile Leak - Grade A (Managed conservatively)'), ('bile_leak_grade_b', 'Bile Leak - Grade B (Requires intervention)'), ('bile_leak_grade_c', 'Bile Leak - Grade C (Reoperation required)'), ('post_hepatectomy_liver_failure', 'Post-hepatectomy Liver Failure'), ('ascites', 'Ascites'), ('portal_vein_thrombosis', 'Portal Vein Thrombosis'), ('hepatic_artery_thrombosis', 'Hepatic Artery Thrombosis'), ('hepatic_vein_obstruction', 'Hepatic Vein Obstruction'), ('other', 'Other')], max_length=50)),
                ('bilirubin_pod5', models.FloatField(blank=True, help_text='Bilirubin on POD 5 (μmol/L)', null=True)),
                ('inr_pod5', models.FloatField(blank=True, help_text='INR on POD 5', null=True)),
                ('drain_bilirubin', models.FloatField(blank=True, help_text='Drain bilirubin (μmol/L)', null=True)),
                ('drain_bilirubin_ratio', models.FloatField(blank=True, help_text='Drain/Serum bilirubin ratio', null=True)),
                ('intervention_required', models.BooleanField(default=False)),
                ('intervention_type', models.CharField(blank=True, help_text='e.g., ERCP, PTBD, Surgery', max_length=100)),
                ('ascites_volume_ml', models.IntegerField(blank=True, help_text='Daily ascites output (mL)', null=True)),
                ('diuretic_required', models.BooleanField(default=False)),
                ('surgical_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_complications', to='clinical.surgicalprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PancreaticComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_days', models.IntegerField(help_text='Postoperative day of onset (0 for intraoperative)')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_days', models.IntegerField(blank=True, help_text='Postoperative day of resolution', null=True)),
                ('clavien_grade', models.IntegerField(choices=[(1, 'Grade I - Any deviation from normal course without need for treatment'), (2, 'Grade II - Pharmacologic treatment required'), (3, 'Grade IIIa - Intervention without general anesthesia'), (4, 'Grade IIIb - Intervention with general anesthesia'), (5, 'Grade IVa - Single organ dysfunction'), (6, 'Grade IVb - Multiorgan dysfunction'), (7, 'Grade V - Death of patient')])),
                ('treatment', models.TextField(blank=True, help_text='Describe treatment provided')),
                ('reoperation_required', models.BooleanField(default=False)),
                ('reoperation_details', models.TextField(blank=True)),
                ('resolved_completely', models.BooleanField(default=True, help_text='Did the complication resolve completely?')),
                ('sequelae', models.TextField(blank=True, help_text='Any long-term sequelae')),
                ('complication_type', models.CharField(choices=[('popf_grade_b', 'POPF - Grade B (Requires intervention)'), ('popf_grade_c', 'POPF - Grade C (Severe, reoperation/death)'), ('delayed_gastric_emptying', 'Delayed Gastric Emptying'), ('post_pancreatectomy_hemorrhage', 'Post-pancreatectomy Hemorrhage'), ('pancreatitis', 'Acute Pancreatitis'), ('pancreatic_necrosis', 'Pancreatic Necrosis'), ('other', 'Other')], max_length=50)),
                ('drain_amylase_pod1', models.FloatField(blank=True, help_text='Drain amylase on POD 1 (U/L)', null=True)),
                ('drain_amylase_pod3', models.FloatField(blank=True, help_text='Drain amylase on POD 3 (U/L)', null=True)),
                ('drain_output_ml', models.IntegerField(blank=True, help_text='Daily drain output (mL)', null=True)),
                ('hemoglobin_drop', models.FloatField(blank=True, help_text='Drop in hemoglobin (g/L)', null=True)),
                ('transfusion_units', models.IntegerField(blank=True, help_text='Units of blood transfused', null=True)),
                ('intervention_type', models.CharField(blank=True, help_text='e.g., Angiography, Surgery', max_length=100)),
                ('nasogastric_days', models.IntegerField(blank=True, help_text='Days with nasogastric tube', null=True)),
                ('surgical_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_complications', to='clinical.surgicalprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
