# Generated by Django 6.0.3 on 2026-03-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_surgicalprocedure_biliary_surgery_subtype_and_more'),
        ('complications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livercomplication',
            name='drain_bilirubin',
        ),
        migrations.RemoveField(
            model_name='livercomplication',
            name='drain_bilirubin_ratio',
        ),
        migrations.RemoveField(
            model_name='livercomplication',
            name='intervention_required',
        ),
        migrations.RemoveField(
            model_name='livercomplication',
            name='intervention_type',
        ),
        migrations.AddField(
            model_name='generalcomplication',
            name='drain_bilirubin',
            field=models.FloatField(blank=True, help_text='Drain bilirubin (μmol/L)', null=True),
        ),
        migrations.AddField(
            model_name='generalcomplication',
            name='drain_bilirubin_ratio',
            field=models.FloatField(blank=True, help_text='Drain/Serum bilirubin ratio', null=True),
        ),
        migrations.AddField(
            model_name='generalcomplication',
            name='intervention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalcomplication',
            name='intervention_type',
            field=models.CharField(blank=True, help_text='e.g., ERCP, PTBD, Surgery', max_length=100),
        ),
        migrations.AddField(
            model_name='livercomplication',
            name='details',
            field=models.TextField(blank=True, help_text='Specific details about the complication'),
        ),
        migrations.AddField(
            model_name='pancreaticcomplication',
            name='details',
            field=models.TextField(blank=True, help_text='Specific details about the complication'),
        ),
        migrations.AddField(
            model_name='pancreaticcomplication',
            name='popf_drain_amylase',
            field=models.FloatField(blank=True, help_text='Drain amylase (U/L)', null=True),
        ),
        migrations.AlterField(
            model_name='generalcomplication',
            name='complication_type',
            field=models.CharField(choices=[('surgical_site_infection', 'Surgical Site Infection'), ('pneumonia', 'Pneumonia'), ('uti', 'Urinary Tract Infection'), ('sepsis', 'Sepsis'), ('dvt', 'Deep Vein Thrombosis'), ('pe', 'Pulmonary Embolism'), ('mi', 'Myocardial Infarction'), ('stroke', 'Stroke'), ('aki', 'Acute Kidney Injury'), ('delirium', 'Delirium'), ('ileus', 'Prolonged Ileus (>5 days)'), ('bleeding', 'Postoperative Bleeding requiring transfusion'), ('anastomotic_leak', 'Anastomotic Leak'), ('bile_leak_grade_a', 'Bile Leak - Grade A (Managed conservatively)'), ('bile_leak_grade_b', 'Bile Leak - Grade B (Requires intervention)'), ('bile_leak_grade_c', 'Bile Leak - Grade C (Reoperation required)'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generalcomplication',
            name='surgical_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_complications', to='clinical.surgicalprocedure'),
        ),
        migrations.AlterField(
            model_name='livercomplication',
            name='complication_type',
            field=models.CharField(choices=[('post_hepatectomy_liver_failure', 'Post-hepatectomy Liver Failure'), ('ascites', 'Ascites'), ('portal_vein_thrombosis', 'Portal Vein Thrombosis'), ('hepatic_artery_thrombosis', 'Hepatic Artery Thrombosis'), ('hepatic_vein_obstruction', 'Hepatic Vein Obstruction'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='livercomplication',
            name='surgical_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liver_complications', to='clinical.surgicalprocedure'),
        ),
        migrations.AlterField(
            model_name='pancreaticcomplication',
            name='surgical_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pancreatic_complications', to='clinical.surgicalprocedure'),
        ),
    ]
