# Generated by Django 6.0.3 on 2026-03-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complications', '0002_remove_livercomplication_drain_bilirubin_and_more'),
        ('complications', '0003_migrate_popf_bile_data'),
    ]

    operations = [
    ]
