# Generated by Django 6.0.3 on 2026-04-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_sarcopeniaassessment'),
        ('complications', '0004_merge_20260330_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='POPFDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('biochemical', 'Biochemical Leak (Grade A - no clinical impact)'), ('grade_b', 'Grade B - Clinically relevant, requires intervention'), ('grade_c', 'Grade C - Severe, reoperation/death')], help_text='ISGPS 2016 POPF Grade', max_length=20)),
                ('drain_amylase_pod3', models.FloatField(blank=True, help_text='Drain amylase on postoperative day 3 (U/L)', null=True)),
                ('drain_amylase_ratio', models.FloatField(blank=True, help_text='Drain/Serum amylase ratio (≥3 indicates fistula)', null=True)),
                ('drain_retained', models.BooleanField(default=False, help_text='Drain retained >3 weeks')),
                ('antibiotics_required', models.BooleanField(default=False, help_text='Antibiotics for infection')),
                ('interventional_radiology', models.BooleanField(default=False, help_text='CT-guided drainage')),
                ('tpn_required', models.BooleanField(default=False, help_text='Total parenteral nutrition required')),
                ('reoperation_required', models.BooleanField(default=False, help_text='Reoperation for POPF')),
                ('icu_admission', models.BooleanField(default=False, help_text='ICU admission due to POPF')),
                ('death_attributed', models.BooleanField(default=False, help_text='Death attributed to POPF')),
                ('resolved_days', models.IntegerField(blank=True, help_text='Days until fistula resolved', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popf_detail', to='clinical.surgicalprocedure')),
            ],
            options={
                'verbose_name': 'POPF Detail (ISGPS)',
                'verbose_name_plural': 'POPF Details (ISGPS)',
            },
        ),
        migrations.CreateModel(
            name='PostHepatectomyLiverFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('grade_a', 'Grade A - Abnormal labs, no clinical deterioration'), ('grade_b', 'Grade B - Deviation from normal course, non-invasive treatment'), ('grade_c', 'Grade C - Invasive treatment required, organ failure')], help_text='ISGLS PHLF Grade', max_length=20)),
                ('bilirubin_pod5', models.FloatField(blank=True, help_text='Bilirubin on postoperative day 5 (μmol/L)', null=True)),
                ('inr_pod5', models.FloatField(blank=True, help_text='INR on postoperative day 5', null=True)),
                ('ascites_requiring_diuretics', models.BooleanField(default=False, help_text='Ascites requiring diuretics')),
                ('encephalopathy_present', models.BooleanField(default=False, help_text='Hepatic encephalopathy')),
                ('coagulopathy_requiring_ffp', models.BooleanField(default=False, help_text='Coagulopathy requiring FFP transfusion')),
                ('renal_failure', models.BooleanField(default=False, help_text='Acute kidney injury requiring RRT')),
                ('respiratory_failure', models.BooleanField(default=False, help_text='Respiratory failure requiring ventilation')),
                ('reoperation_required', models.BooleanField(default=False, help_text='Reoperation for liver failure')),
                ('liver_transplant_required', models.BooleanField(default=False, help_text='Liver transplantation required')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_days', models.IntegerField(blank=True, null=True)),
                ('death_attributed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surgical_procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phlf_detail', to='clinical.surgicalprocedure')),
            ],
            options={
                'verbose_name': 'Post-hepatectomy Liver Failure (ISGLS)',
                'verbose_name_plural': 'Post-hepatectomy Liver Failures (ISGLS)',
            },
        ),
    ]
