# Generated by Django 6.0.3 on 2026-04-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_delete_sarcopeniaassessment'),
        ('complications', '0005_popfdetail_posthepatectomyliverfailure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popfdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posthepatectomyliverfailure',
            options={},
        ),
        migrations.AddField(
            model_name='popfdetail',
            name='pancreatic_complication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popf_detail', to='complications.pancreaticcomplication'),
        ),
        migrations.AddField(
            model_name='posthepatectomyliverfailure',
            name='liver_complication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phlf_detail', to='complications.livercomplication'),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='antibiotics_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='death_attributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='drain_amylase_pod3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='drain_amylase_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='drain_retained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='grade',
            field=models.CharField(choices=[('biochemical', 'Biochemical Leak'), ('grade_b', 'Grade B - Clinically relevant'), ('grade_c', 'Grade C - Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='icu_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='interventional_radiology',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='reoperation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='resolved_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='surgical_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popf_details_backup', to='clinical.surgicalprocedure'),
        ),
        migrations.AlterField(
            model_name='popfdetail',
            name='tpn_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='ascites_requiring_diuretics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='bilirubin_pod5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='coagulopathy_requiring_ffp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='encephalopathy_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='grade',
            field=models.CharField(choices=[('grade_a', 'Grade A - Abnormal labs'), ('grade_b', 'Grade B - Non-invasive treatment'), ('grade_c', 'Grade C - Invasive treatment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='inr_pod5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='liver_transplant_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='renal_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='reoperation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='respiratory_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posthepatectomyliverfailure',
            name='surgical_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phlf_details_backup', to='clinical.surgicalprocedure'),
        ),
    ]
