# Generated by Django 6.0.3 on 2026-03-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator - Full system access'), ('surgeon', 'Surgeon - Full patient data access'), ('resident', 'Resident - Edit access, limited admin'), ('researcher', 'Researcher - Read-only for research'), ('data_entry', 'Data Entry - Create/edit records'), ('viewer', 'View Only - Read-only access')], default='viewer', help_text='User role determines access level', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, help_text='e.g., Dr., Prof., etc.', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('institution_email', models.EmailField(blank=True, help_text='Work email', max_length=254)),
                ('research_interests', models.TextField(blank=True, help_text='Areas of research interest')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
