# Generated by Django 6.0.3 on 2026-04-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymization_level',
            field=models.CharField(choices=[('none', 'No anonymization - full access'), ('partial', 'Partial - Names hidden, dates shifted by ±7 days'), ('full', 'Full - Complete de-identification for research')], default='none', help_text='Level of data anonymization for research users', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('import', 'Import'), ('backup', 'Backup')], max_length=20)),
                ('model_name', models.CharField(help_text='Model accessed (e.g., Patient, SurgicalProcedure)', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object', max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation', max_length=200)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_audit_user_id_29b33e_idx'), models.Index(fields=['model_name', 'object_id'], name='users_audit_model_n_fb8a47_idx'), models.Index(fields=['action', 'timestamp'], name='users_audit_action_962101_idx')],
            },
        ),
    ]
